hotfix: Checkstyle violations config and unit test failure
companieshouse/insolvency-delta-consumer pull request #11
Opened 2022-02-10 12:44 UTC by iichr

2022-02-10 12:45 UTC, kgeddis-ch approved these changes

2022-02-10 12:47 UTC, iichr commented on pom.xml
> +					<violationIgnore>LineLength,CustomImportOrder</violationIgnore>
We use intellij auto-format for both import sequence and line length (inherited limit of 100 is too little) - so we can ignore just those 2 for now

2022-02-10 16:25 UTC, zahidm3 requested changes

2022-02-11 09:33 UTC, iichr commented
Closing as now redundant

2022-02-11 09:33 UTC, closed without merging