DSND-788 : Added integration tests
companieshouse/insolvency-delta-consumer pull request #48
Opened 2022-05-23 11:34 UTC by vchitti-kainos

2022-05-23 14:32 UTC, amobarak submitted a review, later dismissed

2022-05-23 14:54 UTC, zahidm3 requested changes

2022-05-23 14:54 UTC, zahidm3 commented on src/itest/resources/features/insolvency-delta-error-path.feature
> +    Then the message should be moved to topic "insolvency-delta-insolvency-delta-consumer-invalid"
Probably better to create a new "insolvency-delete-flows.feature" file with all delete scenarios, and existing ones (insolvency-delta-error-flows.feature, insolvency-delta-happy-path.feature) will remain untouched to represent three major EPICs we implemented in Insolvency

2022-05-24 08:57 UTC, zahidm3 approved these changes

2022-05-24 09:09 UTC, merged